[phases.setup]
nixPkgs = [
  "python310",
  "chromium"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install-deps chromium",
  "playwright install chromium"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
